winme:
  string:
    hello: "dev"
  constant:
    env: "DEV"
    host: "http://localhost:8080"
logging:
  level:
    com:
      winme:
        controller: DEBUG
    org:
      springframework:
        web: DEBUG
    guru:
      springframework:
        controllers: DEBUG