spring:
  profiles:
    active: "prod"
  main:
    banner-mode: "off"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
digitax:
  constant:
    appName: "digitax"
  swagger:
    host: "localhost:8080"
  email:
    email: "abcd@gmail.com"
    password: "yowjyordbchmbefn"
    host: "smtp.gmail.com"
    port: 587
    auth: true
    enable: true
  google:
    client: "345680725424-evurtenl54vsbg3t6foojaipi72h1ud1.apps.googleusercontent.com"
    geoLocationApi: "AIzaSyAXuBG4_9CkNw1UKgelmpQ6mUHabjwfyYk"
  facebook:
    clientId: "41279cccsafddscxv9156099930"
    clientSecret: "14695df9f165f3acbf04df3sdxzvsdxvcsdxczed45c98ca"

jasypt:
  encryptor:
    password: "master"