digitax:
  string:
    hello: "prod"
  constant:
    env: "DEV"
    host: "digitaxapi-env.eba-nrr834zb.us-east-1.elasticbeanstalk.com:8080"
  swagger:
    host: "digitaxapi-env.eba-nrr834zb.us-east-1.elasticbeanstalk.com:8080"

spring:
  datasource:
       url: "jdbc:mysql://digitax.czsd0zr3qkn2.us-east-1.rds.amazonaws.com:3306/digitax?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
       username: "admin"
       password: "6h3D#[!U:nex~}X~"
logging:
  level:
    com:
      digitax:
        controller: DEBUG
    org:
      springframework:
        web: DEBUG
    guru:
      springframework:
        controllers: DEBUG