//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 08:09:43 PM IST 
//


package com.digitax.soapschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ETINRetrievalRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ETINRetrievalRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestCd" type="{http://www.irs.gov/a2a/mef/MeFMSIServices}TestCdType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETINRetrievalRequestType", propOrder = {
    "testCd"
})
public class ETINRetrievalRequestType {

    @XmlElement(name = "TestCd", required = true)
    protected TestCdType testCd;

    /**
     * Gets the value of the testCd property.
     * 
     * @return
     *     possible object is
     *     {@link TestCdType }
     *     
     */
    public TestCdType getTestCd() {
        return testCd;
    }

    /**
     * Sets the value of the testCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCdType }
     *     
     */
    public void setTestCd(TestCdType value) {
        this.testCd = value;
    }

}
