//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 08:09:43 PM IST 
//


package com.digitax.soapschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormStatusGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormStatusGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FormNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FormStatusTxt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormStatusGrpType", propOrder = {
    "formNum",
    "formStatusTxt"
})
public class FormStatusGrpType {

    @XmlElement(name = "FormNum", required = true)
    protected String formNum;
    @XmlElement(name = "FormStatusTxt", required = true)
    protected String formStatusTxt;

    /**
     * Gets the value of the formNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormNum() {
        return formNum;
    }

    /**
     * Sets the value of the formNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormNum(String value) {
        this.formNum = value;
    }

    /**
     * Gets the value of the formStatusTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormStatusTxt() {
        return formStatusTxt;
    }

    /**
     * Sets the value of the formStatusTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormStatusTxt(String value) {
        this.formStatusTxt = value;
    }

}
