//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 02:15:07 PM IST 
//


package com.digitax.soapschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2"/>
 *         &lt;element name="ETIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppSysID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SessionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TestIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "messageID",
    "action",
    "etin",
    "appSysID",
    "sessionIndicator",
    "testIndicator"
})
public class Message {

    @XmlElement(name = "MessageID")
    protected int messageID;
    @XmlElement(name = "Action", required = true)
    protected List<String> action;
    @XmlElement(name = "ETIN")
    protected String etin;
    @XmlElement(name = "AppSysID")
    protected String appSysID;
    @XmlElement(name = "SessionIndicator")
    protected String sessionIndicator;
    @XmlElement(name = "TestIndicator")
    protected String testIndicator;

    /**
     * Gets the value of the messageID property.
     * 
     */
    public int getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     */
    public void setMessageID(int value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAction() {
        if (action == null) {
            action = new ArrayList<String>();
        }
        return this.action;
    }

    /**
     * Gets the value of the etin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETIN() {
        return etin;
    }

    /**
     * Sets the value of the etin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETIN(String value) {
        this.etin = value;
    }

    /**
     * Gets the value of the appSysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppSysID() {
        return appSysID;
    }

    /**
     * Sets the value of the appSysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppSysID(String value) {
        this.appSysID = value;
    }

    /**
     * Gets the value of the sessionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionIndicator() {
        return sessionIndicator;
    }

    /**
     * Sets the value of the sessionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionIndicator(String value) {
        this.sessionIndicator = value;
    }

    /**
     * Gets the value of the testIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestIndicator() {
        return testIndicator;
    }

    /**
     * Sets the value of the testIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestIndicator(String value) {
        this.testIndicator = value;
    }

}
