//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 08:09:43 PM IST 
//


package com.digitax.soapschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.digitax.soapschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LogoutRequest_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "LogoutRequest");
    private final static QName _LoginRequest_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "LoginRequest");
    private final static QName _GetStateParticipantsListResponse_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "GetStateParticipantsListResponse");
    private final static QName _ETINStatusResponse_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "ETINStatusResponse");
    private final static QName _ETINStatusRequest_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "ETINStatusRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "LoginResponse");
    private final static QName _LogoutResponse_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "LogoutResponse");
    private final static QName _ETINRetrievalResponse_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "ETINRetrievalResponse");
    private final static QName _GetStateParticipantsListRequest_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "GetStateParticipantsListRequest");
    private final static QName _ETINRetrievalRequest_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFMSIServices", "ETINRetrievalRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.digitax.soapschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ETINRetrievalRequestType }
     * 
     */
    public ETINRetrievalRequestType createETINRetrievalRequestType() {
        return new ETINRetrievalRequestType();
    }

    /**
     * Create an instance of {@link GetStateParticipantsListResponseType }
     * 
     */
    public GetStateParticipantsListResponseType createGetStateParticipantsListResponseType() {
        return new GetStateParticipantsListResponseType();
    }

    /**
     * Create an instance of {@link GetStateParticipantsListRequestType }
     * 
     */
    public GetStateParticipantsListRequestType createGetStateParticipantsListRequestType() {
        return new GetStateParticipantsListRequestType();
    }

    /**
     * Create an instance of {@link FormStatusGrpType }
     * 
     */
    public FormStatusGrpType createFormStatusGrpType() {
        return new FormStatusGrpType();
    }

    /**
     * Create an instance of {@link StateParticipantGrpType }
     * 
     */
    public StateParticipantGrpType createStateParticipantGrpType() {
        return new StateParticipantGrpType();
    }

    /**
     * Create an instance of {@link LoginRequestType }
     * 
     */
    public LoginRequestType createLoginRequestType() {
        return new LoginRequestType();
    }

    /**
     * Create an instance of {@link ETINStatusRequestType }
     * 
     */
    public ETINStatusRequestType createETINStatusRequestType() {
        return new ETINStatusRequestType();
    }

    /**
     * Create an instance of {@link LoginResponseType }
     * 
     */
    public LoginResponseType createLoginResponseType() {
        return new LoginResponseType();
    }

    /**
     * Create an instance of {@link LogoutResponseType }
     * 
     */
    public LogoutResponseType createLogoutResponseType() {
        return new LogoutResponseType();
    }

    /**
     * Create an instance of {@link ETINRetrievalResponseType }
     * 
     */
    public ETINRetrievalResponseType createETINRetrievalResponseType() {
        return new ETINRetrievalResponseType();
    }

    /**
     * Create an instance of {@link LogoutRequestType }
     * 
     */
    public LogoutRequestType createLogoutRequestType() {
        return new LogoutRequestType();
    }

    /**
     * Create an instance of {@link ETINStatusResponseType }
     * 
     */
    public ETINStatusResponseType createETINStatusResponseType() {
        return new ETINStatusResponseType();
    }

    /**
     * Create an instance of {@link ETINStatusGrpType }
     * 
     */
    public ETINStatusGrpType createETINStatusGrpType() {
        return new ETINStatusGrpType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "LogoutRequest")
    public JAXBElement<LogoutRequestType> createLogoutRequest(LogoutRequestType value) {
        return new JAXBElement<LogoutRequestType>(_LogoutRequest_QNAME, LogoutRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "LoginRequest")
    public JAXBElement<LoginRequestType> createLoginRequest(LoginRequestType value) {
        return new JAXBElement<LoginRequestType>(_LoginRequest_QNAME, LoginRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStateParticipantsListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "GetStateParticipantsListResponse")
    public JAXBElement<GetStateParticipantsListResponseType> createGetStateParticipantsListResponse(GetStateParticipantsListResponseType value) {
        return new JAXBElement<GetStateParticipantsListResponseType>(_GetStateParticipantsListResponse_QNAME, GetStateParticipantsListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ETINStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "ETINStatusResponse")
    public JAXBElement<ETINStatusResponseType> createETINStatusResponse(ETINStatusResponseType value) {
        return new JAXBElement<ETINStatusResponseType>(_ETINStatusResponse_QNAME, ETINStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ETINStatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "ETINStatusRequest")
    public JAXBElement<ETINStatusRequestType> createETINStatusRequest(ETINStatusRequestType value) {
        return new JAXBElement<ETINStatusRequestType>(_ETINStatusRequest_QNAME, ETINStatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "LoginResponse")
    public JAXBElement<LoginResponseType> createLoginResponse(LoginResponseType value) {
        return new JAXBElement<LoginResponseType>(_LoginResponse_QNAME, LoginResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "LogoutResponse")
    public JAXBElement<LogoutResponseType> createLogoutResponse(LogoutResponseType value) {
        return new JAXBElement<LogoutResponseType>(_LogoutResponse_QNAME, LogoutResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ETINRetrievalResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "ETINRetrievalResponse")
    public JAXBElement<ETINRetrievalResponseType> createETINRetrievalResponse(ETINRetrievalResponseType value) {
        return new JAXBElement<ETINRetrievalResponseType>(_ETINRetrievalResponse_QNAME, ETINRetrievalResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStateParticipantsListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "GetStateParticipantsListRequest")
    public JAXBElement<GetStateParticipantsListRequestType> createGetStateParticipantsListRequest(GetStateParticipantsListRequestType value) {
        return new JAXBElement<GetStateParticipantsListRequestType>(_GetStateParticipantsListRequest_QNAME, GetStateParticipantsListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ETINRetrievalRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", name = "ETINRetrievalRequest")
    public JAXBElement<ETINRetrievalRequestType> createETINRetrievalRequest(ETINRetrievalRequestType value) {
        return new JAXBElement<ETINRetrievalRequestType>(_ETINRetrievalRequest_QNAME, ETINRetrievalRequestType.class, null, value);
    }

}
