//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.12 at 02:15:07 PM IST 
//


package com.digitax.soapschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.digitax.soapschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestIndicator_QNAME = new QName("htttp://www.digitax.com/spring/soap/api/mefService", "TestIndicator");
    private final static QName _SessionIndicator_QNAME = new QName("htttp://www.digitax.com/spring/soap/api/mefService", "SessionIndicator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.digitax.soapschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link MessageRequest }
     * 
     */
    public MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "htttp://www.digitax.com/spring/soap/api/mefService", name = "TestIndicator")
    public JAXBElement<Object> createTestIndicator(Object value) {
        return new JAXBElement<Object>(_TestIndicator_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "htttp://www.digitax.com/spring/soap/api/mefService", name = "SessionIndicator")
    public JAXBElement<Object> createSessionIndicator(Object value) {
        return new JAXBElement<Object>(_SessionIndicator_QNAME, Object.class, null, value);
    }

}
