//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 08:09:43 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.digitax.soapschema;
