//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 07:57:57 PM IST 
//


package gov.irs.a2a.mef.mefheader;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorClassificationCdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ErrorClassificationCdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SYSTEM_ERROR"/>
 *     &lt;enumeration value="RESOURCE_UNAVAILABLE"/>
 *     &lt;enumeration value="MESSAGE_FORMAT_ERROR"/>
 *     &lt;enumeration value="SECURITY_ERROR"/>
 *     &lt;enumeration value="REQUEST_ERROR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ErrorClassificationCdType")
@XmlEnum
public enum ErrorClassificationCdType {

    SYSTEM_ERROR,
    RESOURCE_UNAVAILABLE,
    MESSAGE_FORMAT_ERROR,
    SECURITY_ERROR,
    REQUEST_ERROR;

    public String value() {
        return name();
    }

    public static ErrorClassificationCdType fromValue(String v) {
        return valueOf(v);
    }

}
