//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 07:57:57 PM IST 
//


package gov.irs.a2a.mef.mefheader;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for MeFHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeFHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.irs.gov/a2a/mef/MeFHeader}HeaderMessageIdType"/>
 *         &lt;element name="RelatesTo" type="{http://www.irs.gov/a2a/mef/MeFHeader}HeaderMessageIdType" minOccurs="0"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageTs" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ETIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SessionKeyCd" type="{http://www.irs.gov/a2a/mef/MeFHeader}SessionKeyCdType" minOccurs="0"/>
 *         &lt;element name="TestCd" type="{http://www.irs.gov/a2a/mef/MeFHeader}TestCdType" minOccurs="0"/>
 *         &lt;element name="NotificationResponse" type="{http://www.irs.gov/a2a/mef/MeFHeader}MeFNotificationResponse" minOccurs="0"/>
 *         &lt;element name="AppSysID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WSDLVersionNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClientSoftwareTxt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeFHeaderType", propOrder = {
    "messageID",
    "relatesTo",
    "action",
    "messageTs",
    "etin",
    "sessionKeyCd",
    "testCd",
    "notificationResponse",
    "appSysID",
    "wsdlVersionNum",
    "clientSoftwareTxt"
})
public class MeFHeaderType {

    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "RelatesTo")
    protected String relatesTo;
    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "MessageTs", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar messageTs;
    @XmlElement(name = "ETIN")
    protected String etin;
    @XmlElement(name = "SessionKeyCd")
    protected SessionKeyCdType sessionKeyCd;
    @XmlElement(name = "TestCd")
    protected TestCdType testCd;
    @XmlElement(name = "NotificationResponse")
    protected MeFNotificationResponse notificationResponse;
    @XmlElement(name = "AppSysID", required = true)
    protected String appSysID;
    @XmlElement(name = "WSDLVersionNum", required = true)
    protected String wsdlVersionNum;
    @XmlElement(name = "ClientSoftwareTxt")
    protected String clientSoftwareTxt;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the relatesTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatesTo() {
        return relatesTo;
    }

    /**
     * Sets the value of the relatesTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatesTo(String value) {
        this.relatesTo = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the messageTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMessageTs() {
        return messageTs;
    }

    /**
     * Sets the value of the messageTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMessageTs(XMLGregorianCalendar value) {
        this.messageTs = value;
    }

    /**
     * Gets the value of the etin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETIN() {
        return etin;
    }

    /**
     * Sets the value of the etin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETIN(String value) {
        this.etin = value;
    }

    /**
     * Gets the value of the sessionKeyCd property.
     * 
     * @return
     *     possible object is
     *     {@link SessionKeyCdType }
     *     
     */
    public SessionKeyCdType getSessionKeyCd() {
        return sessionKeyCd;
    }

    /**
     * Sets the value of the sessionKeyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionKeyCdType }
     *     
     */
    public void setSessionKeyCd(SessionKeyCdType value) {
        this.sessionKeyCd = value;
    }

    /**
     * Gets the value of the testCd property.
     * 
     * @return
     *     possible object is
     *     {@link TestCdType }
     *     
     */
    public TestCdType getTestCd() {
        return testCd;
    }

    /**
     * Sets the value of the testCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCdType }
     *     
     */
    public void setTestCd(TestCdType value) {
        this.testCd = value;
    }

    /**
     * Gets the value of the notificationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MeFNotificationResponse }
     *     
     */
    public MeFNotificationResponse getNotificationResponse() {
        return notificationResponse;
    }

    /**
     * Sets the value of the notificationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeFNotificationResponse }
     *     
     */
    public void setNotificationResponse(MeFNotificationResponse value) {
        this.notificationResponse = value;
    }

    /**
     * Gets the value of the appSysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppSysID() {
        return appSysID;
    }

    /**
     * Sets the value of the appSysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppSysID(String value) {
        this.appSysID = value;
    }

    /**
     * Gets the value of the wsdlVersionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWSDLVersionNum() {
        return wsdlVersionNum;
    }

    /**
     * Sets the value of the wsdlVersionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWSDLVersionNum(String value) {
        this.wsdlVersionNum = value;
    }

    /**
     * Gets the value of the clientSoftwareTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientSoftwareTxt() {
        return clientSoftwareTxt;
    }

    /**
     * Sets the value of the clientSoftwareTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSoftwareTxt(String value) {
        this.clientSoftwareTxt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
