//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 07:57:57 PM IST 
//


package gov.irs.a2a.mef.mefheader;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.irs.a2a.mef.mefheader package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MeFHeader_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFHeader", "MeFHeader");
    private final static QName _TransmitterIPAddress_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFHeader", "TransmitterIPAddress");
    private final static QName _ErrorExceptionDetail_QNAME = new QName("http://www.irs.gov/a2a/mef/MeFHeader", "ErrorExceptionDetail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.irs.a2a.mef.mefheader
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeFHeaderType }
     * 
     */
    public MeFHeaderType createMeFHeaderType() {
        return new MeFHeaderType();
    }

    /**
     * Create an instance of {@link ErrorExceptionDetailType }
     * 
     */
    public ErrorExceptionDetailType createErrorExceptionDetailType() {
        return new ErrorExceptionDetailType();
    }

    /**
     * Create an instance of {@link MeFNotificationResponse }
     * 
     */
    public MeFNotificationResponse createMeFNotificationResponse() {
        return new MeFNotificationResponse();
    }

    /**
     * Create an instance of {@link TransmitterIPAddressType }
     * 
     */
    public TransmitterIPAddressType createTransmitterIPAddressType() {
        return new TransmitterIPAddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeFHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFHeader", name = "MeFHeader")
    public JAXBElement<MeFHeaderType> createMeFHeader(MeFHeaderType value) {
        return new JAXBElement<MeFHeaderType>(_MeFHeader_QNAME, MeFHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransmitterIPAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFHeader", name = "TransmitterIPAddress")
    public JAXBElement<TransmitterIPAddressType> createTransmitterIPAddress(TransmitterIPAddressType value) {
        return new JAXBElement<TransmitterIPAddressType>(_TransmitterIPAddress_QNAME, TransmitterIPAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorExceptionDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.irs.gov/a2a/mef/MeFHeader", name = "ErrorExceptionDetail")
    public JAXBElement<ErrorExceptionDetailType> createErrorExceptionDetail(ErrorExceptionDetailType value) {
        return new JAXBElement<ErrorExceptionDetailType>(_ErrorExceptionDetail_QNAME, ErrorExceptionDetailType.class, null, value);
    }

}
