//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 07:57:57 PM IST 
//


package gov.irs.a2a.mef.mefheader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransmitterIPAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmitterIPAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransmitterIPAddressTxt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceivedAtIRSTs" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmitterIPAddressType", propOrder = {
    "transmitterIPAddressTxt",
    "receivedAtIRSTs"
})
public class TransmitterIPAddressType {

    @XmlElement(name = "TransmitterIPAddressTxt", required = true)
    protected String transmitterIPAddressTxt;
    @XmlElement(name = "ReceivedAtIRSTs", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar receivedAtIRSTs;

    /**
     * Gets the value of the transmitterIPAddressTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmitterIPAddressTxt() {
        return transmitterIPAddressTxt;
    }

    /**
     * Sets the value of the transmitterIPAddressTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmitterIPAddressTxt(String value) {
        this.transmitterIPAddressTxt = value;
    }

    /**
     * Gets the value of the receivedAtIRSTs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedAtIRSTs() {
        return receivedAtIRSTs;
    }

    /**
     * Sets the value of the receivedAtIRSTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedAtIRSTs(XMLGregorianCalendar value) {
        this.receivedAtIRSTs = value;
    }

}
