//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 04:05:12 PM IST 
//


package gov.irs.a2a.mef.mefmsiservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.digitax.serpiisbu.SensitiveDenySerializeBase;


/**
 * <p>Java class for LoginResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusTxt" type="{http://www.irs.gov/a2a/mef/MeFMSIServices}login"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginResponseType", propOrder = {
    "statusTxt"
})
public class LoginResponseType extends SensitiveDenySerializeBase {

    @XmlElement(name = "StatusTxt", required = true)
    protected String statusTxt;

    /**
     * Gets the value of the statusTxt property.
     * 
     * @return
     *     possible object is
     *     {@link Login }
     *     
     */
    public String getStatusTxt() {
        return statusTxt;
    }

    /**
     * Sets the value of the statusTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Login }
     *     
     */
    public void setStatusTxt(String value) {
        this.statusTxt = value;
    }

}
