//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.16 at 04:05:12 PM IST 
//


package gov.irs.a2a.mef.mefmsiservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StateParticipantGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateParticipantGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StateCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParticipantProgramsTxt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateParticipantGrpType", propOrder = {
    "stateCd",
    "participantProgramsTxt"
})
public class StateParticipantGrpType {

    @XmlElement(name = "StateCd", required = true)
    protected String stateCd;
    @XmlElement(name = "ParticipantProgramsTxt", required = true)
    protected String participantProgramsTxt;

    /**
     * Gets the value of the stateCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCd() {
        return stateCd;
    }

    /**
     * Sets the value of the stateCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCd(String value) {
        this.stateCd = value;
    }

    /**
     * Gets the value of the participantProgramsTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantProgramsTxt() {
        return participantProgramsTxt;
    }

    /**
     * Sets the value of the participantProgramsTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantProgramsTxt(String value) {
        this.participantProgramsTxt = value;
    }

}
